# Use root/example as user/password credentials
version: '3.1'

services:

  wishlist-db:
    container_name: wishlist-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: asd
      MYSQL_DATABASE: wishlist
      MYSQL_USER: wishlist
      MYSQL_PASSWORD: wishlist
    ports:
      - 3306:3306
    volumes:
      - "./deploy.sql:/docker-entrypoint-initdb.d/1-deploy.sql:ro"

  wishlist-adminer:
    container_name: wishlist-adminer
    image: adminer
    ports:
      - 1234:8080
    depends_on:
      - wishlist-db